version: "3.8"

services:
  db:
    image: postgres:15
    container_name: f1db_container
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: f1db
      POSTGRES_DB: f1db
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4
    container_name: f1db_container
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: robin.gloeggler@study.thws.de
      PGADMIN_DEFAULT_PASSWORD: f1db_admin
    ports:
      - "8080:80"
    networks:
      - backend

volumes:
  db_data:

networks:
  backend:
    driver: bridge
